### ISSUE TITLE
Request data from demo device

### ISSUE THREAD

**Issue by bdv1** [LORD-MicroStrain/SensorCloud#4]
Hello,

I am trying to download sensor data using a URL request. Unfortunately, it is not possible to use data from the actual sensor at this moment, so i want to try data from a demo device.  I am using the username and password to verify the request.

The simplest request was the get channel info request. so this is my request (the username and password are replaced by ...) :

https://www.sensorcloud.com/SensorCloud/devices/<OAPI0039T2KSFD6X>/sensors/<32582>/channels/?version=1&username=<...>&password=<...>

(For some reason " OAPI0039T2KSFD6X>/sensors " is changed into this " OAPI0039T2KSFD6X//sensors ")

Can anybody explain if such a request would be possible and why this link does not work?

Greetings,
Ben

**Comment by brblord** [comment]
Hello Ben,

Our permissions work are a little bit different than the approach you are taking, but I think we can get a working solution in order for you to demo and work out the API calls.

For API access using the username and password, you have to be the "owner" of a device with the username/password authentication option enabled.  Alternatively, there is access with an API key, which we do not provide for our demo devices.  However, I'd be happy to attach a new device to your SensorCloud account with this same data copied over for you to experiment with.  Please email support@sensorcloud.com with just your username referencing this ticket, and we can get the data associated with your account.

One last thing to note, the API requires an authentication call to acquire a token and the API server location before using the other calls.  This is referenced under the [Authentication section](https://github.com/LORD-MicroStrain/SensorCloud/blob/master/API/DeviceMethods.md#authenticate) in the API documentation.  You'll want to note that the authentication host is actually sensorcloud.microstrain.com as well.  Once you've successfully authenticated with either an API key or your username password, all subsequent requests will use "auth_token=<...>" in the query string rather than your authentication credentials.

Best regards,
-Ben
