### ISSUE TITLE
Downloading large time series

### ISSUE THREAD

**Issue by farzami** [LORD-MicroStrain/SensorCloud#5]
I am trying to use 'downloadData' function from example code (Python 3) to download my data from SensorCloud. When I want to download a large time series, only the first 100,000 data points are downloaded. Is this a limitation of SensorCloud API?

**Comment by brblord** [comment]
This is currently a hard limit of the API.  The intention is that for large data sets, the requests are to be split into multiple requests.  Since there isn't a bound on data points in a particular time range, this limit keeps the payload from becoming excessively large.  The two best approaches are to either keep track of the last timestamp and use that as the subsequent start time, or to per-calculate appropriate start/end times based on the sample rate and the 100K limit, and these requests can be made asynchronously.

**Comment by farzami** [comment]
Thank you for the clarification.
